[tool.cibuildwheel]
build-verbosity = 3
build = "cp311-*"
skip = ["*-manylinux_i686", "*-musllinux*"]

[tool.cibuildwheel.linux]
environment = { PATH = "/usr/lib/ccache:/usr/lib64/ccache:/usr/lib/ccache/bin:$PATH", PIP_FIND_LINKS = "https://makslevental.github.io/wheels", PIP_NO_BUILD_ISOLATION = "false" }
before-all = [
    "yum -y install libxml2 ncurses-devel",
    "{project}/scripts/docker_prepare_ccache.sh",
    "{project}/scripts/install_boost.sh",
]
before-build = [
    "pip install -r requirements.txt",
    "{project}/scripts/pip_install_mlir.sh",
]
environment-pass = [
    "APPLY_PATCHES",
    "CIBW_ARCHS",
    "CMAKE_ARGS",
    "CMAKE_GENERATOR",
    "DATETIME",
    "HOST_CCACHE_DIR",
    "MATRIX_OS",
    "MLIR_COMMIT",
    "PARALLEL_LEVEL",
    "PIP_FIND_LINKS",
    "PIP_NO_BUILD_ISOLATION",
]
repair-wheel-command = [
    "auditwheel repair -w {dest_dir} {wheel} --exclude libcuda.so.1 --exclude libvulkan.so.1 --exclude libomp.so --exclude libompd.so"
]

[tool.cibuildwheel.macos]
environment = { PATH = "/usr/local/opt/ccache/libexec:$PATH", PIP_FIND_LINKS = "https://makslevental.github.io/wheels", PIP_NO_BUILD_ISOLATION = "false" }
before-all = [
    "rm -rf {project}/build",
    "rm -rf *egg*",
]
before-build = [
    "pip install -r requirements.txt",
    "{project}/scripts/pip_install_mlir.sh",
]
repair-wheel-command = [
    "delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel} --ignore-missing-dependencies"
]

[tool.cibuildwheel.windows]
environment = { PIP_FIND_LINKS = "https://makslevental.github.io/wheels", PIP_NO_BUILD_ISOLATION = "false" }
before-build = [
    "pip install -r requirements.txt",
    "bash {project}\\scripts\\pip_install_mlir.sh",
]